variables:
# uncomment for the pipeline debug purpose
#  CI_DEBUG_TRACE: "true"
  CI_IMAGE: gitlab.int.toradex.com:4567/oleksandr.suvorov/ci-toolchain-container:linux-kernel-builder
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - empty-stub

prepare_image:
  stage: empty-stub
  image: $CI_IMAGE
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: "1"
  script: |
    echo "Empty test pipeline."
    true
